### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hz97** [hz97/sds192-mp3#1]
- [ ] +1 for having an .Rmd that compiles without errors
- [ ] +1 for including a problem statement (what are you trying to figure out?)
- [ ] +1 for using data from more than one table in your analysis
- [ ] +1 for readable, well-documented code (i.e. appropriate comments, using line breaks, breaking code up into logical chunks, following a style guide)
- [ ] +1 unnecessary messages from R are hidden from being displayed in the HTML
- [ ] 
- [ ] +1 for joining multiple tables using SQL
- [ ] +1 for using precise SQL queries (i.e. requesting only the columns you need, rather than requesting everything and filtering in R)
- [ ] +1 for using efficient SQL queries (i.e. making use of an index column to speed things up, and including a comment indicating this)
- [ ] +1 for using a data graphic to articulate your findings
- [ ] +1 for including relevant external information to your analysis (e.g. important cultural context that the reader might not have, historical events that could be related to what you found, etc.)
- [ ] 
- [ ] +1 for using a GitHub repository and including a link to it at the bottom of your submission
- [ ] +1 for including a (well-supported!) alternate hypothesis / explanation for what you found
- [ ] +0–2 WOW factor: awarded at the professors’ discretion for submissions that are exceptionally compelling
