### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hz97** [hz97/sds192-mp3#3]
- [ ] Are these follow-up films more common today than they used to be? 
Count number of sequels produced per year/5 years/decade

- [ ] Can you trace the evolution of sequels across time in Hollywood?
Analyze the data we got, trend/explosion

- [ ] Are sequels more frequent today? 

- [ ] Is the spacing between a sequel and its original shorter than it used to be?
Calculate the differences between production years
Average the result in terms of year/5 years/decade
